export enum actionsTypes {
  ADD_FAVORITE = 'ADD_FAVORITE',
  REMOVE_FAVORITE = 'REMOVE_FAVORITE',
  GET_POKEMONS = 'GET_POKEMONS',
  GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS',
  GET_POKEMONS_FAIL = 'GET_POKEMONS_FAIL',
  GET_TYPE_POKEMONS = 'GET_TYPE_POKEMONS',
  GET_TYPE_POKEMONS_SUCCESS = 'GET_TYPE_POKEMONS_SUCCESS',
  GET_TYPE_POKEMONS_FAIL = 'GET_TYPE_POKEMONS_FAIL',
}
